#!/bin/bash

echo "=================================================="
echo "  DEPLOY FIREBASE RULES (FIRESTORE + STORAGE)"
echo "=================================================="
echo ""
echo "🔒 Security rules need to be deployed to Firebase"
echo ""
echo "📋 OPTION 1: Firebase Console (Easiest)"
echo "---------------------------------------------------"
echo ""
echo "For FIRESTORE RULES:"
echo "1. Go to: https://console.firebase.google.com/project/duaab89-67c12/firestore/rules"
echo "2. Copy content from: firestore.rules"
echo "3. Paste in the console editor"
echo "4. Click 'Publish'"
echo ""
echo "For STORAGE RULES (⚠️ NEEDED FOR COMMITTEE PHOTOS):"
echo "1. Go to: https://console.firebase.google.com/project/duaab89-67c12/storage/rules"
echo "2. Copy content from: storage.rules"
echo "3. Paste in the console editor"
echo "4. Click 'Publish'"
echo ""
echo "📋 OPTION 2: Firebase CLI (If you have it installed)"
echo "---------------------------------------------------"
echo "Deploy both at once:"
echo "   firebase deploy --only firestore:rules,storage"
echo ""
echo "Or deploy individually:"
echo "   firebase deploy --only firestore:rules"
echo "   firebase deploy --only storage"
echo ""
echo "=================================================="
echo ""
echo "✅ Rules files ready:"
echo "   - firestore.rules (Database security)"
echo "   - storage.rules (File upload security)"
echo ""
echo "📖 Need help? Check: DEPLOY_STORAGE_RULES.md"
echo ""
