#!/bin/bash

echo "=================================================="
echo "  DEPLOY FIRESTORE RULES TO FIREBASE"
echo "=================================================="
echo ""
echo "The Firestore rules have been updated locally but need to be deployed."
echo "Please follow these steps:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/project/duaab89-67c12/firestore/rules"
echo ""
echo "2. Copy ALL the content from your firestore.rules file"
echo ""
echo "3. Paste it in the Firebase Console editor"
echo ""
echo "4. Click the 'Publish' button"
echo ""
echo "Alternatively, if you have Firebase CLI installed:"
echo "   firebase deploy --only firestore:rules"
echo ""
echo "=================================================="
echo ""
echo "Your current rules are ready in: firestore.rules"
echo ""
