// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjsvewykzyltglildzst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqc3Zld3lrenlsdGdsaWxkenN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDMwMzQsImV4cCI6MjA3NDMxOTAzNH0.VbRCnETa75FkTg7kdQuPI5b8Fxdfp_S1xsE05iyBA50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});